#!/bin/sh
#get the script's full path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Vundle
echo "Installing Vundle..."
echo
git clone git@github.com:gmarik/vundle.git $DIR/vim/bundle/vundle
echo
echo "Done."
echo

echo "Linking directories and configuration files..."
echo

#bin
if [ -d $HOME/.bin ]; then 
	echo "A binaries directory already exists, backing it up..."
	mv $HOME/.bin $HOME/.bin.bkp
	echo "The directory was backed up as $HOME/.bin.bkp"
	echo
fi

ln -s $DIR/bin $HOME/.bin

#bash
if [ -f $HOME/.bash_profile ]; then
	echo "The Bash resource file already exists, backing it up..."
	mv $HOME/.bash_profile $HOME/.bash_profile.bkp
	echo "The file was backed up as $HOME/.bash_profile.bkp"
	echo
fi

ln -s $DIR/bash_profile $HOME/.bash_profile

#git config
if [ -f $HOME/.gitconfig ]; then
        echo "Git's global config file already exists, backing it up..."
        mv $HOME/.gitconfig $HOME/.gitconfig.bkp
        echo "The file was backed up as $HOME/.gitconfig.bkp"
        echo
fi

ln -s $DIR/gitconfig $HOME/.gitconfig

#git ignore
if [ -f $HOME/.gitignore_global ]; then
        echo "Git's global ignore file already exists, backing it up..."
        mv $HOME/.gitignore_global $HOME/.gitignore_global.bkp
        echo "The file was backed up as $HOME/.gitignore_global.bkp"
        echo
fi

ln -s $DIR/gitignore $HOME/.gitignore_global

#vimrc
if [ -f $HOME/.vimrc ]; then 
	echo "A Vim resource file already exists, backing it up..."
	mv $HOME/.vimrc $HOME/.vimrc.bkp
	echo "The file was backed up as $HOME/.vimrc.bkp"
	echo
fi

ln -s $DIR/vimrc $HOME/.vimrc
	
#vim dir
if [ -d $HOME/.vim ]; then
	echo "The Vim directory already exists, backing it up..."
	mv $HOME/.vim $HOME/.vim_bkp
	echo "The directory was backed up as $HOME/.vim_bkp"
	echo
fi

ln -s $DIR/im $HOME/.vim

# Vim plugins
echo "Installing Vim plugins..."
echo
vim +BundleInstall +qall
echo

echo "Done, please log out and then back in to make the changes"
echo "to bash effective on Linux, or close and re-open the"
echo "terminal application."
echo

