#!/bin/sh
#get the script's full path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#download Pathogen bundles
echo "Installing Vundle..."
echo
git clone git@github.com:gmarik/vundle.git $DIR/vim/bundle/vundle
echo
echo "Done."
echo

echo "Linking directories and configuration files..."
echo

#bin
if [ -f ~/.bin ]; then 
	echo "A binaries directory already exists, backing it up..."
	mv ~/.bin ~/.bin.bkp
	echo "The directory was backed up as ~/.bin.bkp"
	echo
fi

ln -s $DIR/bin ~/.bin

#vimrc
if [ -f ~/.vimrc ]; then 
	echo "A Vim resource file already exists, backing it up..."
	mv ~/.vimrc ~/.vimrc.bkp
	echo "The file was backed up as ~/.vimrc.bkp"
	echo
fi

ln -s $DIR/vimrc ~/.vimrc
	
#vim dir
if [ -d ~/.vim ]; then
	echo "The Vim directory already exists, backing it up..."
	mv ~/.vim ~/.vim_bkp
	echo "The directory was backed up as ~/.vim_bkp"
	echo
fi

ln -s $DIR/vim ~/.vim

#bash
if [ -f ~/.bash_profile ]; then
	echo "The Bash resource file already exists, backing it up..."
	mv ~/.bash_profile ~/.bash_profile.bkp
	echo "The file was backed up as ~/.bash_profile.bkp"
	echo
fi

ln -s $DIR/bash_profile ~/.bash_profile

#git config
if [ -f ~/.gitconfig ]; then
        echo "Git's global config file already exists, backing it up..."
        mv ~/.gitconfig ~/.gitconfig.bkp
        echo "The file was backed up as ~/.gitconfig.bkp"
        echo
fi

ln -s $DIR/gitconfig ~/.gitconfig

echo "Installing Vim plugins..."
echo
vim +BundleInstall +qall
echo

echo "Done, please log out and then back in to make the changes"
echo "to bash effective on Linux, or close and re-open the"
echo "terminal application."
echo

