#!/bin/sh
#get the script's full path
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#download Pathogen bundles
echo "Installing Vim plugins..."
echo
git submodule init
git submodule update
echo
echo "Done."
echo

echo "Linking configuration files..."
echo

#vimrc
if [ -f ~/.vimrc ]; then 
	echo "A Vim resource file already exists, backing it up..."
	mv ~/.vimrc ~/.vimrc.bkp
	echo "The file was backed up as ~/.vimrc.bkp"
	echo
fi

ln -s $DIR/vimrc ~/.vimrc
	
#vim dir
if [ -d ~/.vim ]; then
	echo "The Vim folder already exists, backing it up..."
	mv ~/.vim ~/.vim_bkp
	echo "The folder was backed up as ~/.vim_bkp"
	echo
fi

ln -s $DIR/vim ~/.vim

#bash
if [ -f ~/.bash_profile ]; then
	echo "The Bash resource file already exists, backing it up..."
	mv ~/.bash_profile ~/.bash_profile.bkp
	echo "The file was backed up as ~/.bash_profile.bkp"
	echo
fi

ln -s $DIR/bash_profile ~/.bash_profile

#git config
if [ -f ~/.gitconfig ]; then
        echo "Git's global config file already exists, backing it up..."
        mv ~/.gitconfig ~/.gitconfig.bkp
        echo "The file was backed up as ~/.gitconfig.bkp"
        echo
fi

ln -s $DIR/gitconfig ~/.gitconfig

echo "Done, please log out and then back in to make the changes"
echo "to bash effective on Linux, or close and re-open the"
echo "terminal application."
echo

