#!/bin/sh

echo "Updating submodules..."
echo

#make sure all the submodules are ready
git submodule init
git submodule update

#update and commit
git submodule foreach git pull origin master
git commit -a -m "Updating submodules"
git push

echo
echo "Done."

